### ISSUE TITLE
Elements default to inline span

### ISSUE THREAD

**Issue by hope-portal-services** [gfazioli/react-animatecss#1]
Maybe I'm missing something, but being able to pass an element type into the animation may give better control. I've just ran into an issue where this package defaults the wrapper to a `<span>` with `display: inline-block` which causes issues in my flex based layout, in this case, other than overriding the global or specific span CSS, I don't have many options.

Being able to pass a type for render would be great in this case, for example:

`<Fade animate={true} el="div"></Fade>`

**Comment by gfazioli** [comment]
@hope-portal-services currently, the animation components are created by `styled-components` and they are not **agnostic**. This means that they must be extended by a tag `span` or `div`.

Anyway, I saw a couple of interesting posts and discussions about the agnostic approach and I'll try to find a good solution for that

**Comment by gfazioli** [comment]
@hope-portal-services I found a good solution. You may use the `as` props to achieve that. For example

```
  <Bounce as="div" animate={true} direction="right" mode="in">
    <h1>Say Hello to React AnimateCSS</h1>
  </Bounce>  
``` 
As you will see, the `Bounce` will be a `div` instead of a default `span`.

Regarding the `display` you might

```
import styled from "styled-components";
import {Bounce}  from "@gfazioli/react-animatecss"

const BounceStyled = styled(Bounce)`
  display: block;
`;
```
Now you can use `BounceStyled` in `display: block`
